# Generated by Django 4.2.21 on 2025-05-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Univrequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_fac_gestionnaire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_reception_departement',
        ),
    ]
