# Generated by Django 4.2.21 on 2025-05-25 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Univrequest', '0002_remove_user_is_fac_gestionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='receptionniste',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_receptionniste': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
