# Generated by Django 4.2.21 on 2025-05-30 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Univrequest', '0003_filiere_receptionniste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(max_length=50)),
                ('taille', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_traitement', models.DateTimeField()),
                ('resultat', models.TextField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRequetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Requetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('descrition', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=10)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('traitee', 'Traité'), ('rejete', 'Rejeté')], default='en_cours', max_length=50)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Univrequest.documents')),
                ('type_requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Univrequest.typerequetes')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequeteRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Univrequest.rapport')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Univrequest.requetes')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu')], default='non_lu', max_length=50)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Univrequest.requetes')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiseAJourRequete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Univrequest.requetes')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoie', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('recu', 'Reçu')], default='envoye', max_length=50)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Univrequest.requetes')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='requete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Univrequest.requetes'),
        ),
    ]
