# Generated by Django 4.2.21 on 2025-05-30 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Univrequest', '0004_documents_rapport_typerequetes_requetes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
