# Generated by Django 4.2.21 on 2025-05-31 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Univrequest', '0005_remove_message_utilisateur_message_destinataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='fichier',
            field=models.FileField(default=7, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='fichiers',
            field=models.ManyToManyField(blank=True, to='Univrequest.documents'),
        ),
        migrations.AddField(
            model_name='message',
            name='sujet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL),
        ),
    ]
