# Generated by Django 4.2.21 on 2025-05-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univrequest', '0006_documents_fichier_message_fichiers_message_sujet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='requete',
        ),
        migrations.RemoveField(
            model_name='requetes',
            name='document',
        ),
        migrations.AddField(
            model_name='requetes',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='requete_documents', to='Univrequest.documents'),
        ),
    ]
