# Generated by Django 4.2.21 on 2025-06-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univrequest', '0008_alter_requetes_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requetes',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('traitee', 'Traité'), ('rejete', 'Rejeté')], default='en_attente', max_length=50),
        ),
    ]
