# Generated by Django 4.2.21 on 2025-06-06 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Univrequest', '0009_alter_requetes_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='date_traitement',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='resultat',
        ),
        migrations.AddField(
            model_name='rapport',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='date_generation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='fichier_pdf',
            field=models.FileField(default='rapports/placeholder.pdf', upload_to='rapports_pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='filtre_description',
            field=models.TextField(default='Généré sans description de filtre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='periode',
            field=models.CharField(choices=[('jour', 'Jour'), ('semaine', 'Semaine'), ('mois', 'Mois'), ('personnalise', 'Date spécifique')], default='jour', max_length=50),
            preserve_default=False,
        ),
    ]
